name: 'FreshRSS'
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
    ports:
      - ${HTTP_PORT}:80
    networks:
      - reverse_proxy
    restart: unless-stopped

networks:
  reverse_proxy:
    external: true