name: "Jellyfin"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/services/jellyfin/config:/config
      - /mnt/raid_mirror/media:/media
    ports:
      - ${JFIN_PORT}:8096
    networks:
      - reverse_proxy
    restart: unless-stopped

networks:
  reverse_proxy:
    external: true
