name: 'Caddy'
services:
  caddy:
    container_name: caddy
    image: caddy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - reverse_proxy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /home/services/caddy/data:/data
      - /home/services/caddy/config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  reverse_proxy:
    external: true
